# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 07:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20171129_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Telefono',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
