# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 07:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20171129_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='NumControl',
            field=models.CharField(blank=True, default='', max_length=8, validators=[django.core.validators.RegexValidator('^\\d{1,8}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Telefono',
            field=models.CharField(blank=True, default='', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
            preserve_default=False,
        ),
    ]
